import React, {Component} from 'react';
import './App.css';

class TranslateInput extends Component {
    constructor(props) {
        super(props);
        this.state = {
            myWord: "",
            translatedWord: ""
        }
    }

    dict = {
        'alloy': 'alaşım',
        'alaşım': 'alloy',
        'angle': 'köşe',
        'köşe':'angle',
        'beam': 'kiriş',
        'kiriş': 'beam',
        'belt': 'kayış',
        'kayış': 'belt',
        'bolt': 'civata',
        'civata': 'bolt',
        'carbide': 'karbür',
        'karbür': 'carbide',
        'cement': 'çimento',
        'çimento': 'cement',
        'cage': 'yatak bileziği',
        'yatak bileziği': 'cage',
        'chain': 'zincir',
        'zincir': 'chain',
        'coefficient of friction': 'sürtünme katsayısı',
        'sürtünme katsayısı': 'coefficient of friction',
        'coating': 'örtme',
        'örtme': 'coating',
        'column': 'sütun',
        'sütun': 'column',
        'drill point': 'matkap ucu',
        'matkap ucu': 'drill point',
        'drum brake': 'kampanalı fren',
        'kampanalı fren': 'drum brake',
        'emery': 'zımpara',
        'zımpara': 'emery',
        'expansion': 'genişleme',
        'genişleme': 'expansion',
        'escalator': 'yürüyen merdiven',
        'yürüyen merdiven': 'escalator',
        'flexibility': 'esneklik',
        'esneklik': 'flexibility',
        'fading': 'sönümleme',
        'hindrance': 'engel',
          engineer: 'mühendis',
          mühendis: 'engineer',
          efficiency: 'verimlilik',
          verimlilik: 'efficiency',
          empirical: 'deneysel',
          deneysel: 'empirical',
        chip: 'yontmak',
        yontmak: 'chip',
        force: 'kuvvet',
        kuvvet: 'force',
        friction: 'sürtünme',
        sürtünme: 'friction',
        'block and tackle': 'palanga takımı',
        'palanga takımı': 'block and tackle',
        lever: 'kaldıraç',
        'kaldıraç': 'lever',
        fulcrum: 'dayanak',
        dayanak: 'fulcrum',
        cement: 'çimento',
        çimento: 'cement',  
        'key': 'kama',
        'kama': 'key',
        'key seat': 'kama yatağı',
        'kama yatağı': 'key seat',
        'key way': 'kama yuvası',
        'kama yuvası': 'key way',
        'killed steel': 'söndürülmüş çelik',
        'söndürülmüş çelik': 'killed steel',
        'knob': 'topuz, tokmak, düğme',
        'knuckle joint': 'press mafsallı pres',
        'press mafsallı pres': 'knuckle joint',
        'knurled nut': 'tırtıllı somun, tırtıllı el ayar somunu',
        'tırtıllı somun': 'knurled nut',
        'knurling': 'tırtıl çekme',
        'tırtıl çekme': 'knurling',
        'knurling tool': 'tırtıl çekme aleti',
        'tırtıl çekme aleti':'knurling tool',
        'labor': 'işçilik',
        'işçilik': 'labor',
        'land': 'faz',
        'faz': 'land',
        'lap joint': 'bindirmeli bağlantı',
        'bindirmeli bağlantı': 'lap point',
        'lap welding': 'bindirmeli kaynak, iki parçayı üst üste bindirerek yapılan kaynak',
        'bindirmeli kaynak': 'lap welding',
        'lapping': 'parlatma',
        'parlatma': 'lapping',
        'lateral': 'yanal torna',
        'yanal torna': 'lateral',
        'lead': 'kurşun',
        'kurşun': 'lead',
        'lead screw': 'vida açma mili',
        'vida açma mili': 'lead screw',
        'leather': 'deri',
        'deri': 'leather',
        'linkage': 'bağlantı',
        'bağlantı': 'linkage',
        'lip angle': 'kenar açısı', 
        'kenar açısı': 'lip angel',
        'lock nut': 'kontra somunu',
        'kontra somunu': 'lock nut',
        'longitudinal': 'uzunlamasına', 
        'uzunlamasına': 'longitudinal',
        'lubricant': 'yağlama maddesi',
        'yağlama maddesi': 'lubricant',
        'lubricating gun': 'yağ tabancası',
        'yağ tabancası': 'lubricating gun',
        'lubrication': 'yağlama',
        'yağlama': 'lubrication',
        'lubricator': 'yağdanlık',
        'yağdanlık': 'lubricator',
        'machinability': 'işlenebilirlik',
        'işlenebilirlik': 'machinability',
        'machine bed': 'tezgah gövdesi',
        'tezgah gövdesi': 'machine bed',
        'machine molding': 'makinalı kalıplama',
        'makinalı kalıplama': 'machine molding',
        'machine screw': 'makina vidası, civata başlı vida, somunlu vida',
        'makina vidası': 'machine screw',
        'machine shop': 'atölye',
        'atölye': 'machine shop',
        'machine tool': 'takım tezgahı',
        'takım tezgahı': 'machine tool',
        'machining time': 'işleme zamanı',
        'işleme zamanı': 'machining time',
        'magnet': 'mıknatıs',
        'mıknatıs': 'magnet',
        'magnetic chuck': 'mıknatıslı ayna',
        'mıknatıslı ayna': 'magnetic chuck',
        'maintenance': 'bakım',
        'bakım': 'maintenance',
        'malleable': 'dövülgen',
        'dövülgen': 'malleable',
        'malleable iron': 'dövülgen demir',
        'dövülgen demir': 'malleable iron',
        'mandrel': 'malafa, torna punta veya matkap başlığı',
        'torna başlığı': 'mandrel',
        'manual': 'elle işleyen, elle çalıştırılan; el kitabı',
        'el kitabı': 'manual',
        'manufacturing  processes': 'imalat yöntemleri',
        'imalat yöntemleri': 'manufacturing processes',
        'martensite': 'martensit',
        'martensit': 'martensite',
        'mash seam weld': 'ezme dikiş kaynağı',
        'ezme dikiş kaynağı': 'mash seam weld',
        'masking': 'maskeleme',
        'maskeleme': 'masking',
        'mass production': 'seri imalat',
        'seri imalat': 'mass production',
        'material': 'malzeme',
        'malzeme': 'material',
        'nail': 'çivi',
        'çivi': 'nail',
        'nail puller': 'kerpeten',
        'kerpeten': 'nail puller',
        'needle': 'iğne',
        'iğne': 'needle',
        'nodular iron': 'yumrulu demir',
        'yumrulu demir': 'nodular iron',
        'nominal size': 'nominal ölçü',
        'nominal ölçü': 'nominal size',
        'nonferrous metal': 'demir içermeyen metal',
        'demir içermeyen metal': 'nonferrous metal',
        'normalizing': 'normalleştirme tavı',
        'normalleştirme tavı': 'normalizing',
        'notching': 'kertikleme',
        'kertikleme': 'notching',
        'numerical control': 'sayısal denetim',
        'sayısal denetim': 'numerical control',
        'nut': 'somun',
        'somun': 'nut',
        'offset': 'sapma',
        'sapma': 'offset',
        'oil': 'yağ',
        'yağ': 'oil',
        'oil bath': 'yağ banyosu',
        'yağ banyosu': 'oil bath',
        'oil screw gun': 'vidalı yağ pompası',
        'vidalı yağ pompası': 'oil screw gun',
        'oil tempered': 'yağda tavlanmış',
        'yağda tavlanmış': 'oil tempered',
        'open-end wrench': 'açık ağız anahtar',
        'açık ağız anahtar': 'open-end wrench',
        'open-hearth furnace': 'siemens-martin fırını',
        'siemens-martin fırını': 'open-hearth furnace',
        'operation': 'işlem',
        'işlem': 'operation',
        'ore': 'cevher',
        'cevher': 'ore',
        'oxidation': 'oksitlenme, paslanma',
        'oksitlenme': 'oxidation',
        'paslanma': 'oxidation',
        'oxy-acetylene welding': 'oksijen kaynağı',
        'oksijen kaynağı': 'oxy-acetylene welding',
        'pattern': 'model (dökümcülükte)',
        'model': 'pattern',
        'pattern allowance': 'kalıp payı',
        'kalıp payı': 'pattern allowance',
        'pellet': 'topak',
        'topak': 'pellet',
        'penetration': 'girinim, penetrasyon',
        'girinim': 'penetration',
        'percussion press': 'vurgu presi',
        'vurgu presi': 'percussion press',
        'perforating': 'delikleme',
        'delikleme': 'perforating',
        'permeability': 'geçirgenlik',
        'geçirgenlik': 'permeability',
        'piercing': 'delme (Mannesman metodu)',
        'delme': 'piercing',
        'pig iron': 'pik demir',
        'pik demir': 'pig iron',
        'pin': 'pim, perno, muylu, şiş, iğne',
        'pim': 'pin',
        'pincers': 'kerpeten',
        'kerpeten': 'pincers',
        'pinion': 'küçük dişli',
        'küçük dişli': 'pinion',
        'pipe': 'boru',
        'boru': 'pipe',
        'pipe wrench': 'boru anahtarı',
        'boru anahtarı': 'pipe wrench',
        'pit molding': 'kuyu dökümü',
        'kuyu dökümü': 'pit molding',
        'pitch': 'hatve, vidanın her dişte ilerleme miktarı, iki diş arasındaki uzaklık, adım',
        'hatve': 'pitch',
        'pitch circle': 'diş açıklığı dairesi, bölme dairesi (dişlide)',
        'diş açıklığı dairesi': 'pitch circle',
        'plain milling cutter': 'silindirik freze bıçağı',
        'silindirik freze bıçağı': 'plain milling cutter',
        'plain milling machine': 'düz freze tezgahı',
        'düz freze tezgahı': 'plain milling machine',
        'planer': 'planya',
        'planya': 'planer',
        'planetary gear': 'gezegen dişli, gezer dişli, planet dişli',
        'planet dişli': 'planetary gear',
        'planetary milling machine': 'gezegen başlı freze tezgahı',
        'gezegen başlı freze tezgahı': 'planetary milling machine',
        'plant': 'fabrika, tesis, atölye',
        'fabrika': 'plant',
        'plastic': 'plastik',
        'plastik': 'plastic',
        'plate': 'levha, plaka',
        'levha': 'plate',
        'plaka': 'plate',
        'plating': 'kaplama',
        'kaplama': 'plating',
        'pliers': 'pense',
        'pense': 'pliers',
        'ploughing force': 'sürtme kuvveti',
        'sürtme kuvveti': 'ploughing force',
        'plug': 'tapa, tıkaç, elektrik fişi',
        'tıkaç': 'plug',
        'elektrik fişi': 'plug',
        'plug gage': 'delik mastarı',
        'delik mastarı': 'plug gage',
        'plumber': 'tesisatçı',
        'tesisatçı': 'plumber',
        'pneumatic gage': 'havalı mastar',
        'havalı mastar': 'pneumatic gage',
        'pneumatic hammer': 'havalı tokmak',
        'havalı tokmak': 'pneumatic hammer',
        'pneumatic rammer': 'havalı (pnömatik) şahmerdan; basınçlı hava tokmağı',
        'havalı şahmerdan': 'pneumatic rammer',
        'point angle': 'uç açısı',
        'uç açısı': 'point angle',
        'pointer': 'gösterge, ibre',
        'gösterge': 'pointer',
        'polishing': 'parlatma, polisaj',
        'polisaj': 'polishing',
        'porosity': 'gözeneklilik',
        'gözeneklilik': 'porosity',
        'powder metallurgy': 'toz metal bilimi',
        'toz metal bilimi': 'powder metallurgy',
        'precipitation hardening': 'çökelterek sertleştirme',
        'çökelterek sertleştirme': 'precipitation hardening',
        'precision': 'hassasiyet',
        'hassasiyet': 'precision',
        'press': 'pres, cendere',
        'pres': 'press',
        'pressing': 'presle şekillendirme, presle basma işlemi',
        'presle şekillendirme': 'pressing',
        'process': 'süreç',
        'süreç': 'process',
        'product': 'ürün',
        'ürün': 'product',
        'production': 'üretim',
        'üretim': 'production',
        'profiling machine': 'kopye tezgahı',
        'kopye tezgahı': 'profiling machine',
        'protractor': 'açı ölçer',
        'açı ölçer': 'protractor',
        'puller': 'çektirme',
        'çektirme': 'puller',
        'pulley': 'kasnak',
        'kasnak': 'pulley',
        'punch': 'zımba',
        'zımba': 'punch',
        'punching': 'zımba ile delme',
        'zımba ile delme': 'punching',
        betül: 'dünyanın en güzel kızı',
        'dünyanın en güzel kızı': 'betül',
        mirkan: 'Uygulamamızı kullandığınız için teşekkür ederiz'
      
      }

    clickTranslate() {
        let val = this.dict[this.state.myWord];
        if(val === undefined) {
            this.setState({translatedWord: "Not in the database, will be added soon"})
        } else {
            this.setState({translatedWord: val})
        }
        
    }

    render() {
        return (
            <div>
                <input className="form" onChange={(e) => {
                    this.setState({myWord: e.target.value.toLowerCase()})
                }}/>
                <h1>{this.state.myWord}</h1>
                <button className="btn" onClick={() => {
                    this.clickTranslate()
                }}>Translate!
                </button>
                <h1>{this.state.translatedWord}</h1>
            </div>
        );
    }
}


class App extends Component {
    render() {
        return (
            <div className="App">
                <header className="container">
                    <TranslateInput/>
                </header>
            </div>
        );
    }
}

export default App;